### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 256dpi** [gomqtt/server#1]
For a first release the following needs to be implemented:

- [ ] Support for secure TCP and WS servers.
- [ ] Proper shutdown after error and on request.
- [ ] Differentiation between temporary and fatal errors.
